package com.pospuc.sisacad.model;
// Generated 22/08/2017 13:55:59 by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Objects;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Curso generated by hbm2java
 */
@Entity
public class Curso implements  Serializable {
    
    private static final long serialVersionUID = 1L;  
    
    @Id
    private Integer id;
    private String nome;
    private Integer idCurriculo;
    private Integer idGradeCurricular;

    public Curso() {
    }

    public Curso(Integer id, String nome) {
        this.id = id;
        this.nome = nome;
    }

    public Curso(Integer id, String nome, Integer idCurriculo, Integer idGradeCurricular) {
        this.id = id;
        this.nome = nome;
        this.idCurriculo = idCurriculo;
        this.idGradeCurricular = idGradeCurricular;
    }

    public Integer getId() {
         return this.id;  
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getIdCurriculo() {
        return this.idCurriculo;
    }

    public void setIdCurriculo(Integer idCurriculo) {
        this.idCurriculo = idCurriculo;
    }

    public Integer getIdGradeCurricular() {
        return this.idGradeCurricular;
    }

    public void setIdGradeCurricular(Integer idGradeCurricular) {
        this.idGradeCurricular = idGradeCurricular;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 97 * hash + Objects.hashCode(this.id);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Curso other = (Curso) obj;
        if (!Objects.equals(this.id, other.id)) {
            return false;
        }
        return true;
    }
    
    
}
